steps:
# [Dataflow]
# Maven package will run compile run the prior phases (validate, compile, test)
# https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases
- name: maven:3.6.0-jdk-8-slim
  waitFor: ['-']
  dir: 'dataflow/java/wordcount'
  entrypoint: 'mvn'
  args: ['package', '-q']
  id: 'build-wordcount-jar'
# Override JAR reference variable to the artifact built in this build to the
# airflow DAG that orchestrates this job picks up this version of the JAR.
- name: 'google/cloud-sdk'
  waitFor: ['build-wordcount-jar']
  dir: 'dataflow/java/wordcount'
  entrypoint: 'bash'
  args: [
          '-c',
    'gcloud composer environments run --location ${_COMPOSER_REGION} ${_COMPOSER_ENV_NAME} variables -- --set dataflow_word_count_jar "wordcount/${_SHORT_SHA}/$(basename $(ls target/word-count-beam-bundled-*.jar))"'
  ]
  id: 'set-composer-jar-ref'
artifacts:
  objects:
    location: 'gs://${_DATAFLOW_JAR_BUCKET}/wordcount/${_SHORT_SHA}/'
    paths: ['./dataflow/java/wordcount/target/word-count-beam-bundled-*.jar']
