project_id        = "datapipelines-ci"
project_num       = "839839114118"
network_name      = "datapipelines-net"
composer_region   = "us-central1"
composer_subnet   = "composer-subnet"
composer_env_name = "datapipelines-orchestration"
env               = "ci"
