project_id        = "datapipelines-prod"
project_num       = "715427528296"
network_name      = "datapipelines-net"
composer_region   = "us-central1"
composer_subnet   = "composer-subnet"
composer_env_name = "datapipelines-orchestration"
env               = "prod"
